# Generated by Django 3.1.6 on 2021-02-10 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_part_datecreated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='desciption',
            new_name='description',
        ),
    ]
