# Generated by Django 3.1.6 on 2021-02-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_auto_20210210_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='part_number_mg',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='part_number_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='part_number_sb',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='image',
            field=models.ImageField(blank=True, upload_to='parts/images/'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_number',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
